import LegalPage from "../legal-page";

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms"
      intro="These terms describe the basic rules for using the ClaimFighter MVP."
    >
      <p>
        ClaimFighter is an informational tool. It helps users understand
        insurance denial letters and draft appeal letters.
      </p>
      <p>
        ClaimFighter does not guarantee claim approval and does not replace a
        lawyer, doctor, insurance professional, or patient advocate.
      </p>
      <p>
        Users are responsible for reviewing all outputs before sending an
        appeal or relying on any information generated by the tool.
      </p>
      <p>
        By using ClaimFighter, users agree to provide only documents they have
        permission to use and to review all generated text carefully.
      </p>
    </LegalPage>
  );
}
